AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-add-npm-packages #magic___^_^___line Sample SAM Template for aws-lambda-add-npm-packages #magic___^_^___line
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  PendoScriptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pendo-script/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        PendoScript:
          Type: Api
          Properties:
            Path: /pendo
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PendoScriptApi:
    Description: "API Gateway endpoint URL for Prod stage for Pendo Script function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pendo/"
  PendoScriptFunction:
    Description: "Pendo Script Function ARN"
    Value: !GetAtt PendoScriptFunction.Arn
  PendoScriptFunctionIamRole:
    Description: "Implicit IAM Role created for Pendo Script function"
    Value: !GetAtt PendoScriptFunctionRole.Arn
